---
# Variables for webserver group

# Nginx configuration
nginx_sites:
  - name: nostalgix
    server_name: nostalgix.org
    listen: 443
    root: /var/www/blog
    ssl: true
    access_log: /var/log/nginx/nostalgix.access.log
    # Redirects for this site
    redirects:
      - from_server_name: www.nostalgix.org
        to_url: https://nostalgix.org$request_uri
      - from_server_name: nostalgix.org
        to_url: https://nostalgix.org$request_uri

  - name: share.nostalgix.org
    server_name: share.nostalgix.org
    listen: 80
    root: /var/www/share
    autoindex: true
    access_log: /var/log/nginx/share.access.log

# SSL/TLS configuration (optional)
nginx_ssl:
  enabled: true # Enable SSL globally since a site uses it
  cert_path: /etc/letsencrypt/live/www.nostalgix.org/fullchain.pem
  key_path: /etc/letsencrypt/live/www.nostalgix.org/privkey.pem

# Let's Encrypt
letsencrypt_webroot: /var/www/letsencrypt
certbot_email: ""  # fill in your email address
certbot_certs:
  - name: www.nostalgix.org
    domains:
      - nostalgix.org
      - www.nostalgix.org
  - name: share.nostalgix.org
    domains:
      - share.nostalgix.org
  - name: brutal.nostalgix.org
    domains:
      - brutal.nostalgix.org
  - name: mail.nostalgix.org
    domains:
      - mail.nostalgix.org

# Application settings
app_user: deployer
app_root: /home/{{ app_user }}/blog
app_port: 3000
